batch_size: 256
root_dir: 'trained_experts'


selector:
    lr: 0.0001
    l2: 0
    num_epochs: 3
    decayRate: 1.0
    
student:
    num_epochs: 1
    lr: 0.0001
    l2: 0
    decayRate: 1.0
    
meta:
    num_epochs: 3
    tlr: 0.0001
    slr: 0.0001
    ilr: 0.0001
    decayRate: 1.0
