root_dir: 'src/trained_expers'
batch_size: 256

selector:
    lr: 0.0001
    l2: 0
    num_epochs: 20
    decayRate: 0.96
    
student:
    num_epochs: 20
    lr: 0.0001
    l2: 0
    decayRate: 1.0
    
meta:
    num_epochs: 20
    tlr: 0.01
    slr: 0.0001
    ilr: 0.001
    decayRate: 0.96
